# Generated by Django 5.2 on 2026-08-27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_user_account_username_ci_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'permissions': [
                    ('manage_platform', 'Can access the Inceptivec Gamification platform portal'),
                    ('publish_core', 'Can publish CORE campaign and release content'),
                    ('manage_organizations', 'Can manage organisations and plan assignments'),
                    ('moderate_scores', 'Can moderate platform scores'),
                    ('view_platform_audit', 'Can view platform audit records'),
                ],
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
