# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('editor_mode', models.CharField(choices=[('SHOOTER', 'Shooter'), ('BOARDING', 'Boarding'), ('BOTH', 'Both')], max_length=16)),
                ('object_type', models.CharField(max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('owner_scope', models.CharField(choices=[('CORE', 'Core'), ('ORGANIZATION', 'Organization'), ('USER', 'User')], default='CORE', max_length=16)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('ORGANIZATION', 'Organization'), ('UNLISTED', 'Unlisted'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16)),
                ('runtime_path', models.CharField(max_length=256)),
                ('thumbnail_path', models.CharField(max_length=256)),
                ('mime_type', models.CharField(max_length=96)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('frame_width', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_height', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_count', models.PositiveIntegerField(blank=True, null=True)),
                ('animation', models.JSONField(blank=True, default=dict)),
                ('collider', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected lowercase SHA-256.')])),
                ('provenance_ref', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_records_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organizations.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
