# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('owner_scope', models.CharField(choices=[('CORE', 'Core'), ('ORGANIZATION', 'Organization'), ('USER', 'User')], max_length=16)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('ORGANIZATION', 'Organization'), ('UNLISTED', 'Unlisted'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_projects_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_projects', to='organizations.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_game_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_releases_created', to=settings.AUTH_USER_MODEL)),
                ('game_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='games.gameproject')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_releases_published', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameproject',
            name='base_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_projects', to='games.gamerelease'),
        ),
        migrations.AddConstraint(
            model_name='gamerelease',
            constraint=models.UniqueConstraint(fields=('game_project', 'version'), name='game_release_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='gameproject',
            constraint=models.UniqueConstraint(fields=('slug', 'owner_scope', 'organization', 'owner_user'), name='game_project_scope_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='gameproject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('owner_scope', 'CORE'), ('owner_user__isnull', True)), models.Q(('organization__isnull', False), ('owner_scope', 'ORGANIZATION'), ('owner_user__isnull', True)), models.Q(('organization__isnull', True), ('owner_scope', 'USER'), ('owner_user__isnull', False)), _connector='OR'), name='game_project_matching_owner_scope'),
        ),
    ]
