# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='game_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='games.gameproject'),
        ),
        migrations.AddField(
            model_name='levelversion',
            name='validation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('game_project', 'slug'), name='level_project_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False)), fields=('game_project', 'campaign', 'sequence'), name='level_project_campaign_sequence_unique'),
        ),
    ]
