# Generated by Django 5.2.17 on 2026-08-25 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(db_index=True)),
                ('display_name', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='game_runs.gamerun')),
            ],
            options={
                'ordering': ['-score', 'published_at'],
                'indexes': [models.Index(fields=['-score', 'published_at'], name='leaderboard_score_1c598b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='leaderboard_score_non_negative')],
            },
        ),
    ]
