# Generated by Django 5.2 on 2026-08-27
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [('games', '0001_initial'), ('levels', '0002_level_game_project_levelversion_validation_report_and_more'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Campaign', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('slug', models.SlugField(max_length=64)), ('name', models.CharField(max_length=128)),
            ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ('game_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='games.gameproject')),
        ]),
        migrations.CreateModel(name='CampaignVersion', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('version', models.PositiveIntegerField()),
            ('lifecycle', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
            ('schema_version', models.CharField(default='1.0', max_length=16)), ('checksum', models.CharField(editable=False, max_length=64)),
            ('validation_report', models.JSONField(blank=True, default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('published_at', models.DateTimeField(blank=True, null=True)),
            ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='campaigns.campaign')),
            ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_versions_created', to=settings.AUTH_USER_MODEL)),
            ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_versions_published', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ['campaign', '-version']}),
        migrations.CreateModel(name='CampaignEntry', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('position', models.PositiveIntegerField()),
            ('entry_kind', models.CharField(choices=[('SHOOTER', 'Shooter'), ('BOARDING_ONLY', 'Boarding only')], default='SHOOTER', max_length=24)),
            ('required', models.BooleanField(default=True)), ('transition', models.JSONField(blank=True, default=dict)),
            ('campaign_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='campaigns.campaignversion')),
            ('level_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_entries', to='levels.levelversion')),
        ], options={'ordering': ['position']}),
        migrations.AddConstraint(model_name='campaign', constraint=models.UniqueConstraint(models.F('game_project'), django.db.models.functions.text.Lower('slug'), name='campaign_project_slug_ci_unique')),
        migrations.AddConstraint(model_name='campaignversion', constraint=models.UniqueConstraint(fields=('campaign', 'version'), name='campaign_version_unique')),
        migrations.AddConstraint(model_name='campaignentry', constraint=models.UniqueConstraint(fields=('campaign_version', 'position'), name='campaign_entry_position_unique')),
        migrations.AddConstraint(model_name='campaignentry', constraint=models.UniqueConstraint(fields=('campaign_version', 'level_version'), name='campaign_entry_level_version_unique')),
    ]
