# Generated by Django 5.2 on 2026-08-27
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [('organizations', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='ServicePlan', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('code', models.CharField(max_length=32, unique=True)),
            ('display_name', models.CharField(max_length=128)), ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
            ('limits', models.JSONField(default=dict)), ('capabilities', models.JSONField(default=dict)), ('sort_order', models.PositiveIntegerField(default=0)),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_plans_created', to=settings.AUTH_USER_MODEL)),
            ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_plans_updated', to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='OrganizationPlanAssignment', fields=[
            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ENDED', 'Ended')], default='ACTIVE', max_length=16)),
            ('plan_snapshot', models.JSONField(default=dict)), ('starts_at', models.DateTimeField()), ('ends_at', models.DateTimeField(blank=True, null=True)),
            ('reason', models.CharField(max_length=240)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
            ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_assignments_created', to=settings.AUTH_USER_MODEL)),
            ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_assignments', to='organizations.organization')),
            ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='plans.serviceplan')),
        ], options={'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('organization',), name='organization_one_active_plan_assignment')]}),
    ]
