export const LEVEL_ONE_SLICE = {
  initialLives: 3,
  playerSpeed: 210,
  playerFireCooldownMs: 280,
  playerLaserSpeed: 300,
  enemyLaserSpeed: 300,
  nukeProjectileSpeed: 547.2,
  scoutRows: 2,
  scoutColumns: 29,
  scoutFireIntervalMs: 1500,
  scoutHorizontalSpeed: 48,
  scoutDropDistance: 10,
  playerDamageCooldownMs: 850,
  bunkerCount: 8,
  initialNukes: 2,
  nukeProjectilePoolSize: 8,
  nukeRearmMax: 150,
} as const;
