# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerprofile_leaderboard_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DELETED_PENDING', 'Deleted pending')], default='ACTIVE', max_length=24),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='display_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='playerprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), name='player_display_name_ci_unique'),
        ),
    ]
