# Generated by Django 5.2.17 on 2026-08-27 06:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_runs', '0003_gamerun_accepted_at_gamerun_duration_ms_and_more'),
        ('levels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('ship_type', models.CharField(default='ALIEN_FRIGATE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_version', models.PositiveIntegerField()),
                ('level_checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Value must be a lowercase SHA-256 hash.')])),
                ('source_entity_id', models.CharField(max_length=128)),
                ('source_entity_type', models.CharField(default='scout', max_length=32)),
                ('source_ship_type', models.CharField(default='ALIEN_FRIGATE', max_length=32)),
                ('anchor_id', models.CharField(max_length=96)),
                ('interior_checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Value must be a lowercase SHA-256 hash.')])),
                ('seed', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('TIMEOUT', 'Timeout'), ('PLAYER_DEAD', 'Player dead'), ('ABORTED', 'Aborted')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_ms', models.PositiveIntegerField(default=60000)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('lives_start', models.PositiveSmallIntegerField()),
                ('lives_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nukes_start', models.PositiveSmallIntegerField()),
                ('nukes_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aliens_killed', models.PositiveSmallIntegerField(default=0)),
                ('containers_opened', models.PositiveSmallIntegerField(default=0)),
                ('lives_found', models.PositiveSmallIntegerField(default=0)),
                ('nukes_found', models.PositiveSmallIntegerField(default=0)),
                ('score_events', models.JSONField(default=list)),
                ('shooter_state_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Value must be a lowercase SHA-256 hash.')])),
                ('return_state', models.JSONField(blank=True, null=True)),
                ('validation_result', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=16)),
                ('validation_code', models.CharField(blank=True, max_length=64)),
                ('capability_token_hash', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Value must be a lowercase SHA-256 hash.')])),
                ('return_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_runs', to='game_runs.gamerun')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_runs', to='levels.level')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('raw_summary', models.JSONField()),
                ('summary_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Value must be a lowercase SHA-256 hash.')])),
                ('accepted', models.BooleanField()),
                ('rejection_code', models.CharField(blank=True, max_length=64)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('boarding_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='boarding.boardingrun')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Value must be a lowercase SHA-256 hash.')])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='boarding.interior')),
            ],
        ),
        migrations.AddField(
            model_name='interior',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='boarding.interiorversion'),
        ),
        migrations.AddField(
            model_name='boardingrun',
            name='interior_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_runs', to='boarding.interiorversion'),
        ),
        migrations.CreateModel(
            name='BoardingRunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Value must be a lowercase SHA-256 hash.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boarding_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='boarding.boardingrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('boarding_run', 'sequence'), name='boarding_event_sequence_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='interiorversion',
            constraint=models.UniqueConstraint(fields=('interior', 'version'), name='boarding_interior_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='boardingrun',
            constraint=models.UniqueConstraint(fields=('game_run', 'level_version', 'anchor_id', 'source_entity_id'), name='boarding_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='boardingrun',
            constraint=models.CheckConstraint(condition=models.Q(('lives_start__gte', 0), ('lives_start__lte', 3), ('nukes_start__gte', 0), ('nukes_start__lte', 2)), name='boarding_start_resources_bounded'),
        ),
        migrations.AddConstraint(
            model_name='boardingrun',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_ms', 60000)), name='boarding_time_limit_exact'),
        ),
    ]
