# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0002_seed_alien_frigate'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interior',
            name='game_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interiors', to='games.gameproject'),
        ),
        migrations.AddField(
            model_name='interiorversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interior_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interiorversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interior_versions_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interiorversion',
            name='schema_version',
            field=models.CharField(default='1.0', max_length=16),
        ),
        migrations.AddField(
            model_name='interiorversion',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='boarding.interiorversion'),
        ),
        migrations.AddField(
            model_name='interiorversion',
            name='validation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interior',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
        migrations.AlterField(
            model_name='interiorversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='interior',
            constraint=models.UniqueConstraint(fields=('game_project', 'slug'), name='interior_project_slug_unique'),
        ),
    ]
