# Generated by Django 5.2.17 on 2026-08-25 02:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('build_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]{0,64}$', 'Build hash must be hexadecimal when provided.')])),
                ('is_active', models.BooleanField(default=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'version'],
            },
        ),
        migrations.CreateModel(
            name='GameRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('web', 'Web'), ('windows', 'Windows'), ('macos', 'macOS'), ('android', 'Android'), ('ios', 'iOS'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('level_reached', models.CharField(blank=True, max_length=32, validators=[django.core.validators.MaxLengthValidator(32)])),
                ('lives_used', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nukes_used', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('victory', models.BooleanField(default=False)),
                ('validity', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_runs', to=settings.AUTH_USER_MODEL)),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_runs', to='game_runs.gameversion')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('event_summary', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]{0,64}$', 'Payload hash must be hexadecimal when provided.')])),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_submission', to='game_runs.gamerun')),
            ],
        ),
        migrations.AddIndex(
            model_name='gamerun',
            index=models.Index(fields=['validity', 'completed_at'], name='game_runs_g_validit_42813d_idx'),
        ),
        migrations.AddIndex(
            model_name='gamerun',
            index=models.Index(fields=['game_version', 'started_at'], name='game_runs_g_game_ve_94b13b_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamerun',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='game_run_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='gamerun',
            constraint=models.CheckConstraint(condition=models.Q(('lives_used__gte', 0)), name='game_run_lives_used_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='gamerun',
            constraint=models.CheckConstraint(condition=models.Q(('nukes_used__gte', 0)), name='game_run_nukes_used_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='gamerun',
            constraint=models.CheckConstraint(condition=models.Q(('client_type__in', ['web', 'windows', 'macos', 'android', 'ios', 'unknown'])), name='game_run_client_type_known'),
        ),
        migrations.AddConstraint(
            model_name='gamerun',
            constraint=models.CheckConstraint(condition=models.Q(('validity__in', ['pending', 'valid', 'rejected'])), name='game_run_validity_known'),
        ),
        migrations.AddIndex(
            model_name='scoresubmission',
            index=models.Index(fields=['submitted_at'], name='game_runs_s_submitt_98755b_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoresubmission',
            constraint=models.CheckConstraint(condition=models.Q(('claimed_score__gte', 0)), name='score_submission_claimed_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='scoresubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='score_submission_idempotency_key_unique'),
        ),
    ]
