# Generated by Django 5.2 on 2026-08-26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('game_runs', '0002_level_identity')]
    operations = [
        migrations.AddField(model_name='gamerun', name='accepted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='gamerun', name='duration_ms', field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name='gamerun', name='lives_end', field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name='gamerun', name='lives_start', field=models.PositiveIntegerField(default=3)),
        migrations.AddField(model_name='gamerun', name='nukes_end', field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name='gamerun', name='nukes_start', field=models.PositiveIntegerField(default=2)),
        migrations.AddField(model_name='gamerun', name='submitted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='gamerun', name='validation_code', field=models.CharField(blank=True, max_length=64)),
        migrations.AddField(model_name='scoresubmission', name='accepted_score', field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name='scoresubmission', name='expected_score', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='scoresubmission', name='rejection_codes', field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name='scoresubmission', name='validated_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='scoresubmission', name='validation_detail', field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name='scoresubmission', name='validation_result', field=models.CharField(default='PENDING', max_length=16)),
    ]
