# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_runs', '0003_gamerun_accepted_at_gamerun_duration_ms_and_more'),
        ('games', '0001_initial'),
        ('levels', '0002_level_game_project_levelversion_validation_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerun',
            name='attempt',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='entry_lives',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='entry_nukes',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='entry_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='entry_state_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='exit_lives',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='exit_nukes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='exit_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='exit_state_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='score_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CampaignRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_capability_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=16)),
                ('next_sequence', models.PositiveSmallIntegerField(default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('lives', models.PositiveSmallIntegerField(default=3)),
                ('nukes', models.PositiveSmallIntegerField(default=2)),
                ('seed_root', models.PositiveBigIntegerField()),
                ('validation_state', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_runs', to='games.gamerelease')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignClaimEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('CLAIMED', 'Claimed'), ('REJECTED', 'Rejected')], max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_claim_events', to=settings.AUTH_USER_MODEL)),
                ('campaign_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_events', to='game_runs.campaignrun')),
            ],
        ),
        migrations.AddField(
            model_name='gamerun',
            name='campaign_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='game_runs.campaignrun'),
        ),
        migrations.AddConstraint(
            model_name='gamerun',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign_run__isnull', False)), fields=('campaign_run', 'sequence', 'attempt'), name='campaign_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anonymous_capability_hash__isnull', True), ('player__isnull', False)), models.Q(('anonymous_capability_hash__isnull', False), ('player__isnull', True)), _connector='OR'), name='campaign_run_single_owner'),
        ),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.CheckConstraint(condition=models.Q(('next_sequence__gte', 1), ('next_sequence__lte', 7)), name='campaign_run_sequence_bounded'),
        ),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.CheckConstraint(condition=models.Q(('lives__gte', 0), ('lives__lte', 3)), name='campaign_run_lives_bounded'),
        ),
        migrations.AddConstraint(
            model_name='campaignrun',
            constraint=models.CheckConstraint(condition=models.Q(('nukes__gte', 0), ('nukes__lte', 2)), name='campaign_run_nukes_bounded'),
        ),
    ]
