# Generated by Django 5.2 on 2026-08-27
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('campaigns', '0001_initial'), ('game_runs', '0004_gamerun_attempt_gamerun_entry_lives_and_more')]
    operations = [
        migrations.RemoveConstraint(model_name='campaignrun', name='campaign_run_sequence_bounded'),
        migrations.RemoveField(model_name='campaignrun', name='next_sequence'),
        migrations.AddField(model_name='campaignrun', name='campaign_version', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='campaigns.campaignversion')),
        migrations.AddField(model_name='campaignrun', name='completed_entry_count', field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name='campaignrun', name='current_entry', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaignentry')),
        migrations.AddField(model_name='campaignrun', name='next_entry', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaignentry')),
        migrations.AddField(model_name='gamerun', name='campaign_entry', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_runs', to='campaigns.campaignentry')),
        migrations.AlterField(model_name='gamerun', name='attempt', field=models.PositiveIntegerField(blank=True, null=True)),
    ]
