# Generated by Django 5.2.17 on 2026-08-27 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('actor_kind', models.CharField(choices=[('USER', 'User'), ('ANONYMOUS', 'Anonymous'), ('SYSTEM', 'System')], max_length=16)),
                ('action', models.CharField(max_length=96)),
                ('target_type', models.CharField(max_length=96)),
                ('target_id', models.CharField(max_length=96)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('FAILED', 'Failed')], max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
